const find = require('lodash').find;
const map = require('lodash').map;

const githubApi = require('./github-api');
const convertToMarkdown = require('./convert-json-to-frontmatter');

function convertToPost(formEntries, date) {
    const templateKey = formEntries.link ? 'embed-post' : 'blog-post';
    return {
        displayPage: 'story-wall',
        templateKey,
        name: formEntries.name,
        date,
        link: formEntries.link,
        occupation: formEntries.occupation,
        source: formEntries.source || '',
        tags: []

    }
}


 function getMasterSha() {
     return githubApi.get('git/refs/head')
         .then((response) => {
             const {
                 body
             } = response;
             const master = find(body, (ele) => ele.ref === 'refs/heads/master');
             return master.object.sha;
         })
 }

exports.handler = function (event, context, callback) {
    if (!event.body) {
        return callback('no body');
    }
    let payload;
    try {
        payload = JSON.parse(event.body).payload;
    } catch (error) {
        console.log(error)
        return callback(`error parsing JSON ${error}`);
    }
    const {
        data
    } = payload;
    const date = new Date();
    const formattedDate = `${date.getFullYear()}-${date.getMonth()}-${date.getDate()}`
    const slugName = `${formattedDate}-${data.name.replace(' ', '-').toLowerCase()}`;
    const newBranchName = `cms/story-wall/${slugName}`;
    const dataToUpload = convertToPost(data, payload.created_at);
    return getMasterSha()
        .then(sha => {
            console.log('got sha', sha)
            const dataToSend = {
                ref: `refs/heads/${newBranchName}`,
                sha,
            }
            return githubApi.post('git/refs', dataToSend)
        })
        .then((returned) => {
            const convertedData = map(dataToUpload, (value, key) => ({
                [key]: value
            }))
            const fileContent = convertToMarkdown({
                frontmatter: convertedData,
                body: data.story
            })
            const base64Content = Buffer.from(fileContent).toString('base64')
            console.log('fileContent', fileContent)
            const dataToSend = {
                message: 'Automatically generated by Netlify Form',
                branch: newBranchName,
                content: base64Content
            }
            return githubApi.put(`contents/src/pages/story-wall/${slugName}.md`, dataToSend)
        })
        .then(() => {
                const dataToSend = {
                    title: `Update Social Media Embed Post "${slugName}"`,
                    head: newBranchName,
                    base: 'master'
                }
                return githubApi.post('pulls', dataToSend)
            })
            .then(returned => {
                console.log(returned.body.issue_url)
                const ref = returned.body.issue_url;
                return githubApi.postFullUrl(`${ref}/labels`, {
                    labels: ['netlify-cms/draft']
                })
            })
        .catch(console.log)
}
